### ISSUE TITLE
Wrong version requirement for bernard/bernard

### ISSUE THREAD

**Issue by FaKeller** [bernardphp/BernardBundle#18]
If I issue `composer require bernard/bernard-bundle` on the command line, composer terminates with the following error message:

    Problem 1
    - Installation request for bernard/bernard-bundle ^1.1 -> satisfiable by bernard/bernard-bundle[1.1.0].
    - bernard/bernard-bundle 1.1.0 requires bernard/bernard 1.0.*@dev -> no matching package found.

Apparently, [Bernard's latest version](https://packagist.org/packages/bernard/bernard) is 0.12.2, so there must be a typo in the composer.json of this bundle.

**Comment by renatomefidf** [comment]
@FaKeller same issue here!
Any updates from the package maintainer?

**Comment by henrikbjorn** [comment]
Tagged 1.1.1 from the 1.x branch, should fix the issue. Thanks for reporting this issue.
