### ISSUE TITLE
Tag 1.1.1?

### ISSUE THREAD

**Issue by fjorgemota** [bernardphp/BernardBundle#27]
Hello.

Tag 1.1.1 is not identified as a release by Github but is what Composer seems to prefer (as it seems more updated, because it's a hotfix update), but...In tag 1.1.1, this commit does not seem to be included: https://github.com/bernardphp/BernardBundle/commit/cf0825f84fee10ea192f4f409eebd7e323984f0e , and so the root key for configuration for Bernard in config.yml seems to be bernard_bernard and not just bernard.

This is not a huge problem, as I can just fix tag 1.1.0 in my composer.json, but it does not seems to be very consistent..So..can you check it and fix it (probably adding a new tag, 1.1.2, with the updates of 1.1.1 and 1.1.0 joined), please?

Thanks. =)

**Comment by acrobat** [comment]
A 1.1.2 tag was pushed some time ago. See: https://github.com/bernardphp/BernardBundle/releases/tag/1.1.2

So closing this issue!
