### ISSUE TITLE
Event when all messages in a queue was processed ?

### ISSUE THREAD

**Issue by Axxon** [bernardphp/BernardBundle#28]
Hello, i search a way to be notified by a event when a specific queue is empty after a series of consume processes in that queue was done (i hope i was clear). Someone could help me ?

**Comment by henrikbjorn** [comment]
There is currently no event for when a queue is empty. Why would you want that (i'm curious :))

**Comment by Axxon** [comment]
Thanks you for you're quick return. In fact that's a little bit tricky, so, i have N process to be execute in the queue, when the queue will be empty after consumers had process the N messages, N is updated. The new N process are performed again. Etc, Etc ... I try to create a infinite cycle of process.

**Comment by henrikbjorn** [comment]
I guess you could get the queue object directly and then perform a count on it.

**Comment by Axxon** [comment]
I thought about that possibility but that means that i will execute a count query at a regular time, first for performance reason that's a bad way and for optimization of the number of messages processed on a not know interval of time, there will be time where the system is on pause, and want that long running process always consume messages.

**Comment by Axxon** [comment]
I use redis for queue system and I'm asking if is there a signal fired when all values are removed for a key. And if i could be notified about it with redis sentinel (that i never used before). But i'm afraid that's a terrible complicated solution.

**Comment by Axxon** [comment]
Ok i had misunderstood your response, in fact you're right. In the consumer class on tick function i could count($queue) if it equal 0 i dispatch a event :)

**Comment by henrikbjorn** [comment]
Redis have some degree of notifications, which you can read about here http://redis.io/topics/notifications. Bernard does not emit any events when a queue is empty. I am not sure such an event is useful and think that a usecase as yours, should be an external system.
