### ISSUE TITLE
New release for symfony 3.0 support

### ISSUE THREAD

**Issue by Anyqax** [bernardphp/BernardBundle#35]
Hi,

could you please tag a new release which includes the composer version requirements change for symfony 3.0 support? The latest 1.1.2 still uses "symfony\/framework-bundle": "~2.1"

thanks

**Comment by fesor** [comment]
There is `2.0.0-alpha1` release published in packagist. It supports Symfony 3.0+.

**Comment by marcin-saja** [comment]
Hi, is there a chance to release new stable version which support Symfony 3.* ?

thanks for your work!

**Comment by fesor** [comment]
As I can see we all waiting for bernard 1.0 release.

Or you could prepare PR for 1.x branch.

**Comment by henrikbjorn** [comment]
I am not sure, the bundle fully supports symfony 3, we should do some testing on that.

**Comment by acrobat** [comment]
I've just released 2.0.1 which should be compatible with bernard/bernard: 2.0.0-alpha5. Symfony 3 support should work! If you encounter any issues, please open a new issue!

**Comment by sagikazarmark** [comment]
I guess you meant 1.0.0-alpha5
