### ISSUE TITLE
Plans for version 2.x

### ISSUE THREAD

**Issue by nlzet** [bernardphp/BernardBundle#36]
Are there any plans on releasing a tag or release for version 2.x ? It seems like I need to install dev-master (branch alias 2.0.x-dev) in order to be able to work with amqp/rabbitmq, but there is no tag available.

Are there open issues for version 2, or just waiting for a release? Build seems to pass.

**Comment by nlzet** [comment]
@henrikbjorn can a new tag be made ?

**Comment by henrikbjorn** [comment]
Tagged 2.0.0-alpha1

**Comment by nlzet** [comment]
Thank you
