### ISSUE TITLE
Configuration node "bernard" does not exist

### ISSUE THREAD

**Issue by byhoratiss** [bernardphp/BernardBundle#37]
Hi there, I'm just trying this bundle and found this problem.
There is no extension able to load the configuration for "bernard".

The configuration node should be: "bernard_bernard"

The guide is wrong? Or it is just a little bug ?

Thanks for this!

**Comment by henrikbjorn** [comment]
It should just be `bernard`

**Comment by byhoratiss** [comment]
I know that "it should be", but Symfony does not recognize the "bernard" node. It looks for a "bernard_bernard" node. Thats why I issue this.

**Comment by henrikbjorn** [comment]
Please create a simple reproduction of this issue, have not had any problems my self or heard anyone else.
