### ISSUE TITLE
iron-mq driver outdated

### ISSUE THREAD

**Issue by jmserra** [bernardphp/BernardBundle#39]
Hi!

I'm trying to use Bernard with the iron-mq driver but seems its expecting the version 1.x of the core library, although they're currently at version 4.x 

Thats tricky as there are major differences between those versions, one of those is that 1.x uses older ironMQ servers and their api version 1, while the 4.x library uses the api v2, and isn't currently possible (as far as i found) use such api version with new ironmq accounts

is there planned any upgrade for such driver?

Thanks a lot!

**Comment by henrikbjorn** [comment]
Feel free to update the driver in Bernard, you can do that directly in your project and then, if you want, submit a PR so i can be replaced.

**Comment by acrobat** [comment]
It seems like this was fixed in bernardphp/bernard#288 and with the latest releases of bernard and the bundle it should all be working fine. Please comment if you still have issues!
