### ISSUE TITLE
When will 2.0 be released?

### ISSUE THREAD

**Issue by ruudk** [bernardphp/BernardBundle#42]

**Comment by henrikbjorn** [comment]
When someone tells me it is stable enough :)

**Comment by ruudk** [comment]
It is :) We use dev-master for a very long time now.

**Comment by henrikbjorn** [comment]
released! Thanks :)

**Comment by ruudk** [comment]
Can BernardBundle 2.0 support Bernard 1.0 :) ?  https://github.com/bernardphp/bernard/tree/1.0.0-alpha4 That one is in Alpha too.

Would be nice to tie them together and remove the https://github.com/bernardphp/BernardBundle/blob/2.0.0/composer.json#L13
