### ISSUE TITLE
Inconsistent dependency configuration

### ISSUE THREAD

**Issue by Disparity** [bernardphp/BernardBundle#44]
Bundle configuration file contains an [updated description of the service](https://github.com/bernardphp/BernardBundle/blob/2.0.0/Resources/config/services.xml#L50) for the changes that are in the [master branch](https://github.com/bernardphp/bernard/blob/master/src/EventListener/FailureSubscriber.php#L21), but absent in the [latest release](https://github.com/bernardphp/bernard/blob/1.0.0-alpha4/src/EventListener/FailureSubscriber.php#L21).

**Comment by acrobat** [comment]
I've just released 2.0.1 which should be compatible with bernard/bernard: 2.0.0-alpha5
