### ISSUE TITLE
What is the most sane way to add a normalizer

### ISSUE THREAD

**Issue by timfennis** [bernardphp/BernardBundle#75]
Hi, I'm trying to use this BernardBundle in my application but I can't for the life of me figure out how to add a Symfony's `GetSetMethodNormalizer` to the `AggregateNormalizer`.

So far I've tried to manually create a service for the `GetSetMethodNormalizer` and tag with with the `bernard.normalizer` tag. But now it always puts this normalizer before the `EnvelopeNormalizer` which breaks everything.

I've also tried overwriting the `bernard.normalizer` service and passing al the normalizers myself, but that doesn't seem to work, nor does it seem like a sane option. (right?)

I've looked through all the source but I can't find any documentation or any indication for how this can be done. If I look at the Bernard documentation it self but that tells me to create the `AggregateNormalizer` myself which seems to defeat the entire purpose of using this bundle.

```
<?php

use Bernard\Normalizer\PlainMessageNormalizer;
use Bernard\Normalizer\EnvelopeNormalizer;
use Bernard\Serializer;
use Normalt\Normalizer\AggregateNormalizer;
use Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer;

$aggregateNormalizer = new AggregateNormalizer([
    new EnvelopeNormalizer(),
    new GetSetMethodNormalizer(),
    new PlainMessageNormalizer(),
]);

$serializer = new Serializer($aggregateNormalizer);
$envelope = $serializer->deserialize($json);
```

**Comment by timfennis** [comment]
I've solved it for now by creating a custom normalizer that only accepts instances of `QueueableCommand` (the interface provided by tactician that I want to normalize). Since this normalizer only accepts instances of this interface it doesn't matter anymore that this normalizer is ahead of the `EnvelopeNormalizer`.

I think a proper answer/example to this question may still benefit other users.

**Comment by henrikbjorn** [comment]
IMO having really specific normalizers are a good idea to have idempotent deserialisation that does not rely on magic. This is important as there is no way of migrating the serialized messages to an updated format

**Comment by timfennis** [comment]
I've come to agree with that. The only issue I guess would be that it took me hours to figure this out, mostly because I got thrown of by the examples in the Bernard documentation. Thanks for the response.
