### ISSUE TITLE
weird behaviour using doctrine driver

### ISSUE THREAD

**Issue by kermorgant** [bernardphp/BernardBundle#79]
Hello,

I've tested alpha9 release of bernard with a sf3.4 project under a small use case having the producer and consumer processes on the same machine.

Having the consumer running in the background, the produced messages were consumed very quickly (and expected mails were sent), but looking at the bernard_messages table, it was empty.

If the consumer is not running, the messages are saved in the bernard_messages table

**Comment by henrikbjorn** [comment]
The doctrine driver will remove the messages from the table when they have been consumed. You can see the code for that here https://github.com/bernardphp/bernard/blob/master/src/Driver/Doctrine/Driver.php#L107

This is the expected behaviour.

**Comment by kermorgant** [comment]
Thanks.

I should have added that on my development environment, those messages are not removed after having ben processed (here, visible flag is set to false).

if this is expected, I fail to see where this behaviour difference is triggered.
